framework:
    workflows:
        order:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Order
            initial_marking: draft
            places:
                - draft
                - new
                - in_process
                - waiting_for_payment
                - ready_for_shipment
                - shipped
                - delivered
                - canceled
                - reversal
            transitions:
                submit:
                    from: draft
                    to: new
                start_processing:
                    from: new
                    to: in_process
                await_payment:
                    from: [new, in_process]
                    to: waiting_for_payment
                payment_received:
                    from: waiting_for_payment
                    to: in_process
                ready_to_ship:
                    from: in_process
                    to: ready_for_shipment
                ship:
                    from: ready_for_shipment
                    to: shipped
                deliver:
                    from: shipped
                    to: delivered
                cancel:
                    from: [draft, new, in_process, waiting_for_payment, ready_for_shipment]
                    to: canceled
                reverse:
                    from: [delivered, shipped]
                    to: reversal
