<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260216172726 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE account_group (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE address (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', client_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', street VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, postal_code VARCHAR(20) DEFAULT NULL, is_billing TINYINT(1) DEFAULT 0 NOT NULL, is_delivery TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, name VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_D4E6F81F92F3E70 (country_id), INDEX idx_address_client (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', account_group_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, code VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, vat_number VARCHAR(50) DEFAULT NULL, purchase_limit NUMERIC(12, 2) DEFAULT NULL, amount_spent NUMERIC(12, 2) DEFAULT NULL, other_phone VARCHAR(20) DEFAULT NULL, other_email VARCHAR(255) DEFAULT NULL, fax VARCHAR(20) DEFAULT NULL, web VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, max_active_users INT DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, is_archived TINYINT(1) DEFAULT 0 NOT NULL, is_legal_entity TINYINT(1) DEFAULT 0 NOT NULL, account_type VARCHAR(50) DEFAULT NULL, UNIQUE INDEX UNIQ_C744045577153098 (code), INDEX IDX_C7440455869A3BF1 (account_group_id), INDEX idx_client_code (code), INDEX idx_client_name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client_product_price (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', client_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', price DOUBLE PRECISION NOT NULL, discount_percentage DOUBLE PRECISION DEFAULT NULL, valid_from DATETIME DEFAULT NULL, valid_until DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_1C2263B119EB6921 (client_id), INDEX IDX_1C2263B14584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact_entity (id INT UNSIGNED AUTO_INCREMENT NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, full_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, phone_2 VARCHAR(255) DEFAULT NULL, home_phone VARCHAR(255) DEFAULT NULL, secondary_email VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, date_of_birth DATE DEFAULT NULL, is_active INT UNSIGNED DEFAULT NULL, description LONGTEXT DEFAULT NULL, account_id VARCHAR(36) DEFAULT NULL, title_id INT UNSIGNED DEFAULT NULL, department_id INT UNSIGNED DEFAULT NULL, support_person_id INT UNSIGNED DEFAULT NULL, level_of_support_id INT UNSIGNED DEFAULT NULL, entity_type_id SMALLINT UNSIGNED NOT NULL, attribute_set_id SMALLINT UNSIGNED NOT NULL, created DATETIME NOT NULL, modified DATETIME NOT NULL, entity_state_id SMALLINT UNSIGNED DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact_title_entity (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, uid VARCHAR(255) DEFAULT NULL, is_custom INT UNSIGNED DEFAULT NULL, entity_type_id SMALLINT UNSIGNED NOT NULL, attribute_set_id SMALLINT UNSIGNED NOT NULL, created DATETIME NOT NULL, modified DATETIME NOT NULL, entity_state_id SMALLINT UNSIGNED DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE country (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', tax_type_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, code VARCHAR(2) NOT NULL, iso31661_alpha3_code VARCHAR(3) DEFAULT NULL, european_union TINYINT(1) DEFAULT 0 NOT NULL, default_tax_percent NUMERIC(5, 2) DEFAULT NULL, dhl_zone INT DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_5373C96677153098 (code), INDEX IDX_5373C96684042C99 (tax_type_id), INDEX idx_country_code (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE delivery_price (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', delivery_type_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) DEFAULT NULL, dhl_zone INT DEFAULT NULL, postal_code_from VARCHAR(20) DEFAULT NULL, postal_code_to VARCHAR(20) DEFAULT NULL, exclude_postal_codes LONGTEXT DEFAULT NULL, size_from NUMERIC(10, 4) DEFAULT NULL, size_to NUMERIC(10, 4) DEFAULT NULL, price_base NUMERIC(10, 2) NOT NULL, delivery_days INT DEFAULT NULL, step_starts_at NUMERIC(10, 4) DEFAULT NULL, for_every_next_size NUMERIC(10, 4) DEFAULT NULL, price_base_step NUMERIC(10, 2) DEFAULT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_DAC3C44BCF52334D (delivery_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE delivery_type (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', warehouse_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, short_description LONGTEXT DEFAULT NULL, remote_code VARCHAR(50) DEFAULT NULL, remote_id VARCHAR(50) DEFAULT NULL, color VARCHAR(50) DEFAULT NULL, is_delivery TINYINT(1) DEFAULT 1 NOT NULL, max_weight NUMERIC(10, 2) DEFAULT NULL, gross_factor NUMERIC(5, 4) DEFAULT NULL, hide_if_not_applicable TINYINT(1) DEFAULT 0 NOT NULL, allow_recurring_payment TINYINT(1) DEFAULT 0 NOT NULL, use_as_default TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, ready_for_shop TINYINT(1) DEFAULT 0 NOT NULL, sort_order INT DEFAULT 0 NOT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_5D429FB35080ECDE (warehouse_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE department_entity (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, entity_type_id SMALLINT UNSIGNED NOT NULL, attribute_set_id SMALLINT UNSIGNED NOT NULL, created DATETIME NOT NULL, modified DATETIME NOT NULL, entity_state_id SMALLINT UNSIGNED DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE discount (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, date_valid_from DATETIME DEFAULT NULL, date_valid_to DATETIME DEFAULT NULL, priority INT DEFAULT NULL, discount_percent NUMERIC(12, 4) DEFAULT NULL, rules LONGTEXT DEFAULT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE documentation (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, category VARCHAR(100) DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, is_published TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_73D5A93B989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE documentation_revision (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', documentation_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', edited_by_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', content LONGTEXT NOT NULL, title LONGTEXT NOT NULL, edited_at DATETIME NOT NULL, change_note VARCHAR(255) DEFAULT NULL, revision_number INT NOT NULL, INDEX IDX_2E88A189C703EEC9 (documentation_id), INDEX IDX_2E88A189DD7B2EBC (edited_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fuel_surcharge (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', delivery_type_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) DEFAULT NULL, date DATE DEFAULT NULL, fuel_surcharge NUMERIC(12, 4) DEFAULT NULL, size_from NUMERIC(12, 4) DEFAULT NULL, size_to NUMERIC(12, 4) DEFAULT NULL, price_base NUMERIC(12, 4) DEFAULT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_129F149CCF52334D (delivery_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE import_manual_entity (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', type_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', status_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', file VARCHAR(255) DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, file_type VARCHAR(5) DEFAULT NULL, size VARCHAR(255) DEFAULT NULL, file_source VARCHAR(255) DEFAULT NULL, date_started DATETIME DEFAULT NULL, date_finished DATETIME DEFAULT NULL, import_result LONGTEXT DEFAULT NULL, rows_imported INT DEFAULT NULL, input_parameters LONGTEXT DEFAULT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, created_by VARCHAR(255) DEFAULT NULL, modified_by VARCHAR(255) DEFAULT NULL, INDEX IDX_137D1F09C54C8C93 (type_id), INDEX IDX_137D1F096BF700BD (status_id), INDEX IDX_137D1F09A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE import_manual_status_entity (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) DEFAULT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE import_manual_type_entity (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) DEFAULT NULL, manager_code VARCHAR(255) DEFAULT NULL, method VARCHAR(255) DEFAULT NULL, estimated_duration INT DEFAULT NULL, manual_type_code VARCHAR(255) DEFAULT NULL, send_email TINYINT(1) DEFAULT NULL, email_template_code VARCHAR(255) DEFAULT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media_item (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', product_document_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', documentation_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', payment_type_document_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', delivery_type_document_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', warehouse_document_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', filename VARCHAR(255) NOT NULL, mime_type VARCHAR(255) NOT NULL, file_path VARCHAR(255) NOT NULL, file_size INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_DC5CFACD4584665A (product_id), INDEX IDX_DC5CFACD6F10E628 (product_document_id), INDEX IDX_DC5CFACDC703EEC9 (documentation_id), INDEX IDX_DC5CFACDC7FED518 (payment_type_document_id), INDEX IDX_DC5CFACDCD4F35F3 (delivery_type_document_id), INDEX IDX_DC5CFACD31069942 (warehouse_document_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `order` (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', dispatched_by_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', cancelled_by_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', order_number VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, total_amount DOUBLE PRECISION NOT NULL, notes LONGTEXT DEFAULT NULL, shipping_address VARCHAR(255) DEFAULT NULL, billing_address VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, is_draft TINYINT(1) NOT NULL, last_saved_at DATETIME DEFAULT NULL, tracking_number VARCHAR(100) DEFAULT NULL, tracking_carrier VARCHAR(50) DEFAULT NULL, tracking_url VARCHAR(500) DEFAULT NULL, dispatched_at DATETIME DEFAULT NULL, cancellation_reason LONGTEXT DEFAULT NULL, cancelled_at DATETIME DEFAULT NULL, INDEX IDX_F52993984FF50408 (dispatched_by_id), INDEX IDX_F5299398187B2D12 (cancelled_by_id), INDEX idx_order_status (status), INDEX idx_order_created_at (created_at), INDEX idx_order_user_id (user_id), INDEX idx_order_number (order_number), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_item (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', order_ref_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', quantity INT NOT NULL, unit_price DOUBLE PRECISION NOT NULL, subtotal DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, is_custom_price TINYINT(1) NOT NULL, INDEX IDX_52EA1F09E238517C (order_ref_id), INDEX IDX_52EA1F094584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_log (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', order_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', changed_by_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', previous_status VARCHAR(50) NOT NULL, new_status VARCHAR(50) NOT NULL, comment LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, metadata JSON DEFAULT NULL, INDEX IDX_CC6427A5828AD0A0 (changed_by_id), INDEX idx_order_log_order (order_id), INDEX idx_order_log_created_at (created_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE packaging_price (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) DEFAULT NULL, size_from NUMERIC(12, 4) DEFAULT NULL, size_to NUMERIC(12, 4) DEFAULT NULL, price_base NUMERIC(12, 4) NOT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE password_reset_token (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', created_by_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', token VARCHAR(128) NOT NULL, status VARCHAR(20) NOT NULL, expires_at DATETIME NOT NULL, used_at DATETIME DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, created_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_6B7BA4B65F37A13B (token), INDEX IDX_6B7BA4B6B03A8386 (created_by_id), INDEX idx_password_reset_token (token), INDEX idx_password_reset_user (user_id), INDEX idx_password_reset_expires_at (expires_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_type (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, short_description LONGTEXT DEFAULT NULL, provider_code VARCHAR(50) DEFAULT NULL, configuration JSON DEFAULT NULL, enable_installments TINYINT(1) DEFAULT 0 NOT NULL, remote_code VARCHAR(50) DEFAULT NULL, fiscal_code VARCHAR(50) DEFAULT NULL, payment_fee NUMERIC(10, 2) DEFAULT NULL, min_cart_total NUMERIC(10, 2) DEFAULT NULL, max_cart_total NUMERIC(10, 2) DEFAULT NULL, color VARCHAR(50) DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, allow_recurring_payment TINYINT(1) DEFAULT 0 NOT NULL, recurring_days_reminder INT DEFAULT NULL, use_as_default TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, sort_order INT DEFAULT 0 NOT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', featured_image_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, part_no VARCHAR(50) DEFAULT NULL, short_description LONGTEXT DEFAULT NULL, unit VARCHAR(50) DEFAULT NULL, price DOUBLE PRECISION NOT NULL, weight VARCHAR(50) DEFAULT NULL, technical_description LONGTEXT DEFAULT NULL, machine_text LONGTEXT DEFAULT NULL, statistic VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, ready_for_shop TINYINT(1) DEFAULT 0 NOT NULL, qty INT DEFAULT NULL, qty_step INT DEFAULT NULL, quote_item_limit INT DEFAULT NULL, fixed_qty INT DEFAULT NULL, product_group_id VARCHAR(36) DEFAULT NULL, catalog_code VARCHAR(100) DEFAULT NULL, retail_price DOUBLE PRECISION DEFAULT NULL, tax_type_id VARCHAR(36) DEFAULT NULL, currency VARCHAR(10) DEFAULT \'EUR\', discount_percent DOUBLE PRECISION DEFAULT NULL, discount_price DOUBLE PRECISION DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_D34A04AD3569D950 (featured_image_id), INDEX idx_product_part_no (part_no), INDEX idx_product_name (name), INDEX idx_product_slug (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_discount (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id VARCHAR(36) NOT NULL, discount_price_base NUMERIC(12, 4) DEFAULT NULL, discount_price_retail NUMERIC(12, 4) DEFAULT NULL, rebate NUMERIC(12, 4) DEFAULT NULL, type INT UNSIGNED DEFAULT NULL, date_valid_from DATETIME DEFAULT NULL, date_valid_to DATETIME DEFAULT NULL, applied_to VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_group (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', parent_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', featured_image_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, product_group_code VARCHAR(50) DEFAULT NULL, level INT DEFAULT 0 NOT NULL, total_products INT DEFAULT 0 NOT NULL, show_on_homepage TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, sort_order INT DEFAULT 0 NOT NULL, meta_title VARCHAR(255) DEFAULT NULL, meta_description LONGTEXT DEFAULT NULL, meta_keywords LONGTEXT DEFAULT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_CC9C3F99989D9B62 (slug), INDEX IDX_CC9C3F99727ACA70 (parent_id), INDEX IDX_CC9C3F993569D950 (featured_image_id), INDEX idx_product_group_slug (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_product_link (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', parent_product_id VARCHAR(36) NOT NULL, child_product_id VARCHAR(36) NOT NULL, relation_type_id INT UNSIGNED DEFAULT NULL, ord INT UNSIGNED DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE refresh_tokens (id INT AUTO_INCREMENT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid DATETIME NOT NULL, UNIQUE INDEX UNIQ_9BACE7E1C74F2195 (refresh_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE support_ticket (id CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', attachment_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', subject VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, order_id VARCHAR(50) DEFAULT NULL, machine VARCHAR(255) DEFAULT NULL, urgency VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_1F5A4D53464E68B (attachment_id), INDEX IDX_1F5A4D53A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tax_type (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, percent NUMERIC(5, 2) NOT NULL, remote_id INT DEFAULT NULL, remote_code VARCHAR(50) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `user` (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', client_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', email VARCHAR(180) NOT NULL, username VARCHAR(180) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone_number VARCHAR(15) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, failed_login_attempts INT DEFAULT 0 NOT NULL, locked_until DATETIME DEFAULT NULL, last_failed_login_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), INDEX IDX_8D93D64919EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_invitation (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', client_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', created_by_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', email VARCHAR(180) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, token VARCHAR(128) NOT NULL, status VARCHAR(20) NOT NULL, expires_at DATETIME NOT NULL, completed_at DATETIME DEFAULT NULL, roles JSON NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_567AA74E5F37A13B (token), INDEX IDX_567AA74E19EB6921 (client_id), INDEX IDX_567AA74EB03A8386 (created_by_id), INDEX idx_user_invitation_token (token), INDEX idx_user_invitation_email (email), INDEX idx_user_invitation_status (status), INDEX idx_user_invitation_expires_at (expires_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE warehouse (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, code VARCHAR(50) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, office_name VARCHAR(255) DEFAULT NULL, url LONGTEXT DEFAULT NULL, latitude VARCHAR(50) DEFAULT NULL, longitude VARCHAR(50) DEFAULT NULL, show_as_location TINYINT(1) DEFAULT 0 NOT NULL, monday_from TIME DEFAULT NULL, monday_to TIME DEFAULT NULL, tuesday_from TIME DEFAULT NULL, tuesday_to TIME DEFAULT NULL, wednesday_from TIME DEFAULT NULL, wednesday_to TIME DEFAULT NULL, thursday_from TIME DEFAULT NULL, thursday_to TIME DEFAULT NULL, friday_from TIME DEFAULT NULL, friday_to TIME DEFAULT NULL, saturday_from TIME DEFAULT NULL, saturday_to TIME DEFAULT NULL, sunday_from TIME DEFAULT NULL, sunday_to TIME DEFAULT NULL, description LONGTEXT DEFAULT NULL, contact_person VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, ready_for_shop TINYINT(1) DEFAULT 0 NOT NULL, keep_url TINYINT(1) DEFAULT 0 NOT NULL, auto_generate_url TINYINT(1) DEFAULT 0 NOT NULL, remote_id INT DEFAULT NULL, legacy_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_ECB38BFCF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F8119EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F81F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455869A3BF1 FOREIGN KEY (account_group_id) REFERENCES account_group (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_product_price ADD CONSTRAINT FK_1C2263B119EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE client_product_price ADD CONSTRAINT FK_1C2263B14584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C96684042C99 FOREIGN KEY (tax_type_id) REFERENCES tax_type (id)');
        $this->addSql('ALTER TABLE delivery_price ADD CONSTRAINT FK_DAC3C44BCF52334D FOREIGN KEY (delivery_type_id) REFERENCES delivery_type (id)');
        $this->addSql('ALTER TABLE delivery_type ADD CONSTRAINT FK_5D429FB35080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id)');
        $this->addSql('ALTER TABLE documentation_revision ADD CONSTRAINT FK_2E88A189C703EEC9 FOREIGN KEY (documentation_id) REFERENCES documentation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE documentation_revision ADD CONSTRAINT FK_2E88A189DD7B2EBC FOREIGN KEY (edited_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE fuel_surcharge ADD CONSTRAINT FK_129F149CCF52334D FOREIGN KEY (delivery_type_id) REFERENCES delivery_type (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE import_manual_entity ADD CONSTRAINT FK_137D1F09C54C8C93 FOREIGN KEY (type_id) REFERENCES import_manual_type_entity (id)');
        $this->addSql('ALTER TABLE import_manual_entity ADD CONSTRAINT FK_137D1F096BF700BD FOREIGN KEY (status_id) REFERENCES import_manual_status_entity (id)');
        $this->addSql('ALTER TABLE import_manual_entity ADD CONSTRAINT FK_137D1F09A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE media_item ADD CONSTRAINT FK_DC5CFACD4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE media_item ADD CONSTRAINT FK_DC5CFACD6F10E628 FOREIGN KEY (product_document_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE media_item ADD CONSTRAINT FK_DC5CFACDC703EEC9 FOREIGN KEY (documentation_id) REFERENCES documentation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE media_item ADD CONSTRAINT FK_DC5CFACDC7FED518 FOREIGN KEY (payment_type_document_id) REFERENCES payment_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE media_item ADD CONSTRAINT FK_DC5CFACDCD4F35F3 FOREIGN KEY (delivery_type_document_id) REFERENCES delivery_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE media_item ADD CONSTRAINT FK_DC5CFACD31069942 FOREIGN KEY (warehouse_document_id) REFERENCES warehouse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F5299398A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993984FF50408 FOREIGN KEY (dispatched_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F5299398187B2D12 FOREIGN KEY (cancelled_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F09E238517C FOREIGN KEY (order_ref_id) REFERENCES `order` (id)');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F094584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE order_log ADD CONSTRAINT FK_CC6427A58D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id)');
        $this->addSql('ALTER TABLE order_log ADD CONSTRAINT FK_CC6427A5828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE password_reset_token ADD CONSTRAINT FK_6B7BA4B6A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE password_reset_token ADD CONSTRAINT FK_6B7BA4B6B03A8386 FOREIGN KEY (created_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD3569D950 FOREIGN KEY (featured_image_id) REFERENCES media_item (id)');
        $this->addSql('ALTER TABLE product_group ADD CONSTRAINT FK_CC9C3F99727ACA70 FOREIGN KEY (parent_id) REFERENCES product_group (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product_group ADD CONSTRAINT FK_CC9C3F993569D950 FOREIGN KEY (featured_image_id) REFERENCES media_item (id)');
        $this->addSql('ALTER TABLE support_ticket ADD CONSTRAINT FK_1F5A4D53464E68B FOREIGN KEY (attachment_id) REFERENCES media_item (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE support_ticket ADD CONSTRAINT FK_1F5A4D53A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D64919EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE user_invitation ADD CONSTRAINT FK_567AA74E19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE user_invitation ADD CONSTRAINT FK_567AA74EB03A8386 FOREIGN KEY (created_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFCF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE address DROP FOREIGN KEY FK_D4E6F8119EB6921');
        $this->addSql('ALTER TABLE address DROP FOREIGN KEY FK_D4E6F81F92F3E70');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455869A3BF1');
        $this->addSql('ALTER TABLE client_product_price DROP FOREIGN KEY FK_1C2263B119EB6921');
        $this->addSql('ALTER TABLE client_product_price DROP FOREIGN KEY FK_1C2263B14584665A');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C96684042C99');
        $this->addSql('ALTER TABLE delivery_price DROP FOREIGN KEY FK_DAC3C44BCF52334D');
        $this->addSql('ALTER TABLE delivery_type DROP FOREIGN KEY FK_5D429FB35080ECDE');
        $this->addSql('ALTER TABLE documentation_revision DROP FOREIGN KEY FK_2E88A189C703EEC9');
        $this->addSql('ALTER TABLE documentation_revision DROP FOREIGN KEY FK_2E88A189DD7B2EBC');
        $this->addSql('ALTER TABLE fuel_surcharge DROP FOREIGN KEY FK_129F149CCF52334D');
        $this->addSql('ALTER TABLE import_manual_entity DROP FOREIGN KEY FK_137D1F09C54C8C93');
        $this->addSql('ALTER TABLE import_manual_entity DROP FOREIGN KEY FK_137D1F096BF700BD');
        $this->addSql('ALTER TABLE import_manual_entity DROP FOREIGN KEY FK_137D1F09A76ED395');
        $this->addSql('ALTER TABLE media_item DROP FOREIGN KEY FK_DC5CFACD4584665A');
        $this->addSql('ALTER TABLE media_item DROP FOREIGN KEY FK_DC5CFACD6F10E628');
        $this->addSql('ALTER TABLE media_item DROP FOREIGN KEY FK_DC5CFACDC703EEC9');
        $this->addSql('ALTER TABLE media_item DROP FOREIGN KEY FK_DC5CFACDC7FED518');
        $this->addSql('ALTER TABLE media_item DROP FOREIGN KEY FK_DC5CFACDCD4F35F3');
        $this->addSql('ALTER TABLE media_item DROP FOREIGN KEY FK_DC5CFACD31069942');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F5299398A76ED395');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993984FF50408');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F5299398187B2D12');
        $this->addSql('ALTER TABLE order_item DROP FOREIGN KEY FK_52EA1F09E238517C');
        $this->addSql('ALTER TABLE order_item DROP FOREIGN KEY FK_52EA1F094584665A');
        $this->addSql('ALTER TABLE order_log DROP FOREIGN KEY FK_CC6427A58D9F6D38');
        $this->addSql('ALTER TABLE order_log DROP FOREIGN KEY FK_CC6427A5828AD0A0');
        $this->addSql('ALTER TABLE password_reset_token DROP FOREIGN KEY FK_6B7BA4B6A76ED395');
        $this->addSql('ALTER TABLE password_reset_token DROP FOREIGN KEY FK_6B7BA4B6B03A8386');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD3569D950');
        $this->addSql('ALTER TABLE product_group DROP FOREIGN KEY FK_CC9C3F99727ACA70');
        $this->addSql('ALTER TABLE product_group DROP FOREIGN KEY FK_CC9C3F993569D950');
        $this->addSql('ALTER TABLE support_ticket DROP FOREIGN KEY FK_1F5A4D53464E68B');
        $this->addSql('ALTER TABLE support_ticket DROP FOREIGN KEY FK_1F5A4D53A76ED395');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D64919EB6921');
        $this->addSql('ALTER TABLE user_invitation DROP FOREIGN KEY FK_567AA74E19EB6921');
        $this->addSql('ALTER TABLE user_invitation DROP FOREIGN KEY FK_567AA74EB03A8386');
        $this->addSql('ALTER TABLE warehouse DROP FOREIGN KEY FK_ECB38BFCF92F3E70');
        $this->addSql('DROP TABLE account_group');
        $this->addSql('DROP TABLE address');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE client_product_price');
        $this->addSql('DROP TABLE contact_entity');
        $this->addSql('DROP TABLE contact_title_entity');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE delivery_price');
        $this->addSql('DROP TABLE delivery_type');
        $this->addSql('DROP TABLE department_entity');
        $this->addSql('DROP TABLE discount');
        $this->addSql('DROP TABLE documentation');
        $this->addSql('DROP TABLE documentation_revision');
        $this->addSql('DROP TABLE fuel_surcharge');
        $this->addSql('DROP TABLE import_manual_entity');
        $this->addSql('DROP TABLE import_manual_status_entity');
        $this->addSql('DROP TABLE import_manual_type_entity');
        $this->addSql('DROP TABLE media_item');
        $this->addSql('DROP TABLE `order`');
        $this->addSql('DROP TABLE order_item');
        $this->addSql('DROP TABLE order_log');
        $this->addSql('DROP TABLE packaging_price');
        $this->addSql('DROP TABLE password_reset_token');
        $this->addSql('DROP TABLE payment_type');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_discount');
        $this->addSql('DROP TABLE product_group');
        $this->addSql('DROP TABLE product_product_link');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE support_ticket');
        $this->addSql('DROP TABLE tax_type');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE user_invitation');
        $this->addSql('DROP TABLE warehouse');
    }
}
